# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-14 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160406_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa_info',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=1, verbose_name='\u8bc4\u5206'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qa_info',
            name='problem_description',
            field=models.TextField(unique_for_date=b'data', verbose_name='\u95ee\u9898\u63cf\u8ff0'),
        ),
    ]
