# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-13 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170614_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qa_info',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='qa_info',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='\u4e25\u91cd\u7a0b\u5ea6'),
        ),
    ]
