# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190513_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HR_employee_number', models.CharField(max_length=100, verbose_name='\u5458\u5de5\u7f16\u53f7')),
                ('HR_employee_name', models.CharField(max_length=100, verbose_name='\u5458\u5de5\u59d3\u540d')),
                ('HR_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Department', verbose_name='\u53d7\u68c0\u5355\u4f4d')),
                ('HR_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Team', verbose_name='\u8d23\u4efb\u73ed\u7ec4')),
            ],
        ),
    ]
